version: '3'

services:
  server:
    image: lab2-net-tech-server
    container_name: server
    env_file: .env
    networks:
      simple_network:
        ipv4_address: 190.150.200.2

  client:
    image: lab2-net-tech-client
    container_name: client
    env_file: .env
    networks:
      simple_network:
        ipv4_address: 190.150.200.7

networks:
  simple_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 190.150.200.0/16
